# Generated by Django 3.2.6 on 2021-08-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('y1_points', models.FloatField(blank=True, max_length=100, null=True)),
                ('y2_points', models.FloatField(blank=True, max_length=100, null=True)),
                ('y3_points', models.FloatField(blank=True, max_length=100, null=True)),
                ('y1_average', models.FloatField(blank=True, max_length=100, null=True)),
                ('y2_average', models.FloatField(blank=True, max_length=100, null=True)),
                ('y3_average', models.FloatField(blank=True, max_length=100, null=True)),
                ('y1_games', models.IntegerField(blank=True, null=True)),
                ('y2_games', models.IntegerField(blank=True, null=True)),
                ('y3_games', models.IntegerField(blank=True, null=True)),
                ('y1_price', models.IntegerField(blank=True, null=True)),
                ('y2_price', models.IntegerField(blank=True, null=True)),
                ('y3_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
