# Generated by Django 3.2.6 on 2021-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lastseasonttl',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(default='Healthy', max_length=100),
        ),
    ]
