# Generated by Django 3.2.6 on 2021-10-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210818_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerGamePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
