# Generated by Django 3.2.6 on 2021-10-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pergamepoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergamepoints',
            name='player_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pergamepoints',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
