# Generated by Django 3.2.6 on 2021-10-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211005_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerGamePoints',
        ),
    ]
